language: node_js

sudo: required

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - docker-compose up --no-start build
  - docker-compose run build bash -c "yarn install --ignore-engines"

install: true # to avoid the default install step

script:
  - docker-compose run --rm build bin/no-only
  - docker-compose run build bash -c "yarn lint"
  - docker-compose run build bash -c "yarn test"

before_deploy:
  - docker-compose run build bash -c "yarn deploy:prepare"

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_API_TOKEN
    src: ./npm-constructicon
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: styleguide
    on:
      tags: true

after_deploy:
  - docker-compose run --rm build bin/announce
